// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDvV9wtSVNqpt0zK-HOicybz2QhWRLulj4',
    appId: '1:1053540422169:web:d29f0ab6f7e670fe4c9088',
    messagingSenderId: '1053540422169',
    projectId: 'vib-database',
    authDomain: 'vib-database.firebaseapp.com',
    storageBucket: 'vib-database.appspot.com',
    measurementId: 'G-F0NKPFZD8C',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDIcyC5kKwiK3hsed4NaxEj6Z82fY9Dhuc',
    appId: '1:1053540422169:android:64f183c104dc8b794c9088',
    messagingSenderId: '1053540422169',
    projectId: 'vib-database',
    storageBucket: 'vib-database.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDHyevST1cYQbCnEYWe7_fXYIBiRon2v3A',
    appId: '1:1053540422169:ios:9e0edd49b097bcab4c9088',
    messagingSenderId: '1053540422169',
    projectId: 'vib-database',
    storageBucket: 'vib-database.appspot.com',
    iosClientId: '1053540422169-nsfauftq245638opghocoknd40i6m6l2.apps.googleusercontent.com',
    iosBundleId: 'com.example.backend',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDHyevST1cYQbCnEYWe7_fXYIBiRon2v3A',
    appId: '1:1053540422169:ios:9e0edd49b097bcab4c9088',
    messagingSenderId: '1053540422169',
    projectId: 'vib-database',
    storageBucket: 'vib-database.appspot.com',
    iosClientId: '1053540422169-nsfauftq245638opghocoknd40i6m6l2.apps.googleusercontent.com',
    iosBundleId: 'com.example.backend',
  );
}
